### ISSUE TITLE
 In rendering to 'pdf', the contents with chinese words will all trun to '??'. Why?

### ISSUE THREAD

**Issue by Amamatthew** [vernes/PHPReport#12]
I found when I render my array datas to 'pdf', the content with chinese words will all trun to '??'.
But the datas above will render correctly, whether in 'html' or 'xls' rendering.
How can I fix it?
[Report 2016-07-15.pdf](https://github.com/vernes/PHPReport/files/365312/Report.2016-07-15.pdf)

**Comment by vernes** [comment]
I have no idea. If it is only pdf, maybe it is a bug in phpexcel? Did you try using phpexcel directly to export files?

**Comment by Amamatthew** [comment]
I used the domPDF(one of the famous PDF Lib) as the PHPExcel's PDF plugin. And I enclosed with a domPDF's DEMO of Rendering the HTML as PDF BELOW for you.

//Render the HTML as PDF
// include autoloader
//require_once 'dompdf/autoload.inc.php';

require_once './autoload.inc.php';

// reference the Dompdf namespace
use Dompdf\Dompdf;

// instantiate and use the dompdf class
$dompdf = new Dompdf();

$html = '<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/></head>
<body>
    <p style="font-family: simsun;">献给母亲的爱</p>
</body>
</html>';

//$dompdf->loadHtml('hello world');
$dompdf->loadHtml($html, 'UTF-8');

// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4', 'landscape');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
$dompdf->stream();

//ps. 
//Pay attention to the line below in the code above PLEASE.
//It told the domPDF to render the paragraph with font-family 'simsum'.
//The 'simsum' is just one of famous Chinese basic local font-family.
//And we should install 'simsum' first before we rendering with it
//See detail in url below:
//https://github.com/dompdf/dompdf/wiki/UnicodeHowTo#configure-dompdf-for-unicode-support

//But I just dont know how to specify a font-family in the PHPReport PDF outputing.
//It seems no where to specify it.
//Any other country's local font PDF output user had the same problem? I don't know.
//Eager the people who meets the same problem  can get a perfect solution( to specify the local font-family).
//Any hints please tell me,thank you!

<p style="font-family: simsun;">献给母亲的爱</p>

**Comment by vernes** [comment]
PHPReport is just using PHPExcel pdf rendering:
```
private function renderPdf($filename)
{
    header('Content-Type: application/vnd.pdf');
    header('Content-Disposition: attachment;filename="'.$filename.'.pdf"');
    header('Cache-Control: max-age=0');
    $this->objWriter = PHPExcel_IOFactory::createWriter($this->objPHPExcel, 'PDF');
    $this->objWriter->save('php://output');
    exit();
 }
```

I have checked PHPExcel code and I haven't seen an option to change generated HTML.

That's why I asked did you try using PHPExcel only. [documentation](https://github.com/PHPOffice/PHPExcel/blob/7d1c140974a4988f8a9739d167335d24fb59955e/Documentation/markdown/Overview/10-Reading-and-Writing.md#pdf)

**Comment by Amamatthew** [comment]
Well thank you for your in time explaining in file line 204~219 of PHPReport.php I find the function below. It seems a good news for us to set the font-family by ourself through add one line:
$this->objPHPExcel->getDefaultStyle()->getFont()->setName('simsun'); 
You can have a try.
	/**
	 * Creates PHPExcel object and template for report
	 */
	private function createTemplate()
	{
		$this->objPHPExcel = new PHPExcel();
		$this->objPHPExcel->setActiveSheetIndex(0);
		$this->objWorksheet = $this->objPHPExcel->getActiveSheet();
		//TODO: other parameters
		$this->objWorksheet->getPageSetup()->setOrientation(PHPExcel_Worksheet_PageSetup::ORIENTATION_PORTRAIT);
		$this->objWorksheet->getPageSetup()->setPaperSize(PHPExcel_Worksheet_PageSetup::PAPERSIZE_A4);
		$this->objWorksheet->getPageSetup()->setHorizontalCentered(true);
		$this->objWorksheet->getPageSetup()->setVerticalCentered(false);
        
        $this->_usingTemplate=false;
	}
