### ISSUE TITLE
Publish in packagist for composer install

### ISSUE THREAD

**Issue by nicolastavella** [vernes/PHPReport#19]
Hi! I have forked a solution for publish the library in packagist.org
I think you must do the same for expose the library to composer...

¿What do you think about it?

[Here is the fork](https://github.com/nicolastavella/phpreport)

**Comment by vernes** [comment]
Nice! I really didn't have time to maintain this, but it's good to see interest. There are some other forks also... 
I'm glad you found it useful, keep it up!
